name: NN_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.7
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - lcms2=2.16
  - lerc=4.0.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - pytorch=2.5.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.13.3
  - tk=8.6.14
  - torchvision=0.20.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - pandas==2.2.3
      - pyparsing==3.2.3
      - pytz==2025.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - threadpoolctl==3.6.0
      - tzdata==2025.2
prefix: /Users/f0064z8/anaconda3/envs/NN_env
