name: NN_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=openblas
  - brotli-python=1.0.9=py311h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py311h313beb8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - filelock=3.13.1=py311hca03da5_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.2=h80987f9_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - idna=3.7=py311hca03da5_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.0.2=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py311hca03da5_0
  - jpeg=9e=h80987f9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.5.1=hc9ead59_1
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=py311hca03da5_0
  - numpy=2.0.1=py311he598dae_1
  - numpy-base=2.0.1=py311hfbfe69c_1
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.4.1=h81ee809_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311h84e58ab_0
  - pip=25.0=py311hca03da5_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=5.9.0=py311h80987f9_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.11=hb885b13_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - pytorch=2.5.1=py3.11_0
  - pyyaml=6.0.2=py311h80987f9_0
  - pyzmq=26.2.0=py311h313beb8_0
  - readline=8.2=h1a28f6b_0
  - requests=2.32.3=py311hca03da5_1
  - setuptools=75.8.0=py311hca03da5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=py311hca03da5_1
  - tk=8.6.14=h6ba3021_0
  - torchvision=0.20.1=py311_cpu
  - tornado=6.4.2=py311h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=py311hca03da5_0
  - urllib3=2.3.0=py311hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.56.0
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - pandas==2.2.3
      - pyparsing==3.2.3
      - pytz==2025.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - threadpoolctl==3.6.0
      - tzdata==2025.2
prefix: /Users/f0064z8/anaconda3/envs/NN_env
